const fs = require('fs');
const path = require('path');

const newTranslations = {
  // BmiCalculator
  "Underweight": { en: "Underweight", ro: "Subponderal", de: "Untergewicht", es: "Bajo peso", it: "Sottopeso", fr: "Insuffisance pondérale", ru: "Недостаточный вес" },
  "Normal Weight": { en: "Normal Weight", ro: "Greutate Normală", de: "Normalgewicht", es: "Peso normal", it: "Normopeso", fr: "Poids normal", ru: "Нормальный вес" },
  "Overweight": { en: "Overweight", ro: "Supraponderal", de: "Übergewicht", es: "Sobrepeso", it: "Sovrappeso", fr: "Surpoids", ru: "Избыточный вес" },
  "Request Gastric Balloon Info": { en: "Request Gastric Balloon Info", ro: "Solicită Info Balon Gastric", de: "Info zu Magenballon anfordern", es: "Solicitar información de Balón Gástrico", it: "Richiedi Info Palloncino Gastrico", fr: "Demander Info Ballon Gastrique", ru: "Запросить информацию о желудочном баллоне" },
  "Obesity Class I": { en: "Obesity Class I", ro: "Obezitate Clasa I", de: "Adipositas Grad I", es: "Obesidad Clase I", it: "Obesità Classe I", fr: "Obésité Classe I", ru: "Ожирение I степени" },
  "Get a Free Evaluation": { en: "Get a Free Evaluation", ro: "Obțineți Evaluare Gratuită", de: "Kostenlose Bewertung erhalten", es: "Obtener una Evaluación Gratuita", it: "Ottieni una Valutazione Gratuita", fr: "Obtenir une Évaluation Gratuite", ru: "Получить бесплатную оценку" },
  "Obesity Class II–III": { en: "Obesity Class II–III", ro: "Obezitate Clasa II–III", de: "Adipositas Grad II–III", es: "Obesidad Clase II–III", it: "Obesità Classe II-III", fr: "Obésité Classe II-III", ru: "Ожирение II-III степени" },
  "Request Bariatric Consultation": { en: "Request Bariatric Consultation", ro: "Solicită Consultație Bariatrică", de: "Bariatrische Beratung anfordern", es: "Solicitar Consulta Bariátrica", it: "Richiedi Consulto Bariatrico", fr: "Demander une Consultation Bariatrique", ru: "Запросить бариатрическую консультацию" },
  "Medical BMI Screening Tool": { en: "Medical BMI Screening Tool", ro: "Instrument Medical de Screening IMC", de: "Medizinisches BMI-Screening-Tool", es: "Herramienta Médica de Evaluación de IMC", it: "Strumento Medico di Screening IMC", fr: "Outil Médical de Dépistage IMC", ru: "Медицинский инструмент для скрининга ИМТ" },
  "BMI Calculator & ": { en: "BMI Calculator & ", ro: "Calculator IMC & ", de: "BMI-Rechner & ", es: "Calculadora de IMC y ", it: "Calcolatore IMC & ", fr: "Calculateur d'IMC & ", ru: "Калькулятор ИМТ и " },
  "Bariatric Check": { en: "Bariatric Check", ro: "Verificare Bariatrică", de: "Bariatrischer Check", es: "Revisión Bariátrica", it: "Controllo Bariatrico", fr: "Vérification Bariatrique", ru: "Бариатрическая проверка" },
  "Calculate your BMI instantly. Our algorithm analyses gender, age and height to provide a medically personalised result.": { en: "Calculate your BMI instantly. Our algorithm analyses gender, age and height to provide a medically personalised result.", ro: "Calculați IMC-ul instantaneu. Algoritmul nostru analizează sexul, vârsta și înălțimea pentru un rezultat medical personalizat.", de: "Berechnen Sie Ihren BMI sofort. Unser Algorithmus analysiert Geschlecht, Alter und Größe, um ein medizinisch personalisiertes Ergebnis zu liefern.", es: "Calcule su IMC al instante. Nuestro algoritmo analiza género, edad y altura para proporcionar un resultado médicamente personalizado.", it: "Calcola il tuo IMC all'istante. Il nostro algoritmo analizza sesso, età e altezza per fornire un risultato medicamente personalizzato.", fr: "Calculez votre IMC instantanément. Notre algorithme analyse le sexe, l'âge et la taille pour fournir un résultat médicalement personnalisé.", ru: "Рассчитайте свой ИМТ мгновенно. Наш алгоритм анализирует пол, возраст и рост, чтобы предоставить индивидуальный медицинский результат." },
  "Gender": { en: "Gender", ro: "Sex", de: "Geschlecht", es: "Género", it: "Genere", fr: "Genre", ru: "Пол" },
  "Select gender": { en: "Select gender", ro: "Selectați sexul", de: "Geschlecht auswählen", es: "Seleccionar género", it: "Seleziona genere", fr: "Sélectionnez le genre", ru: "Выберите пол" },
  "♂ Male": { en: "♂ Male", ro: "♂ Masculin", de: "♂ Männlich", es: "♂ Masculino", it: "♂ Maschio", fr: "♂ Homme", ru: "♂ Мужской" },
  "♀ Female": { en: "♀ Female", ro: "♀ Feminin", de: "♀ Weiblich", es: "♀ Femenino", it: "♀ Femmina", fr: "♀ Femme", ru: "♀ Женский" },
  "Age (years)": { en: "Age (years)", ro: "Vârstă (ani)", de: "Alter (Jahre)", es: "Edad (años)", it: "Età (anni)", fr: "Âge (ans)", ru: "Возраст (лет)" },
  "Height (cm)": { en: "Height (cm)", ro: "Înălțime (cm)", de: "Größe (cm)", es: "Altura (cm)", it: "Altezza (cm)", fr: "Taille (cm)", ru: "Рост (см)" },
  "Weight (kg)": { en: "Weight (kg)", ro: "Greutate (kg)", de: "Gewicht (kg)", es: "Peso (kg)", it: "Peso (kg)", fr: "Poids (kg)", ru: "Вес (кг)" },
  "Analyse My BMI": { en: "Analyse My BMI", ro: "Analizați IMC-ul Meu", de: "Meinen BMI analysieren", es: "Analizar mi IMC", it: "Analizza il mio IMC", fr: "Analyser mon IMC", ru: "Проанализировать мой ИМТ" },
  "Your BMI:": { en: "Your BMI:", ro: "IMC-ul dumneavoastră:", de: "Ihr BMI:", es: "Su IMC:", it: "Il tuo IMC:", fr: "Votre IMC :", ru: "Ваш ИМТ:" },
  "Under": { en: "Under", ro: "Sub", de: "Unter", es: "Bajo", it: "Sotto", fr: "Sous", ru: "Недостаток" },
  "Normal": { en: "Normal", ro: "Normal", de: "Normal", es: "Normal", it: "Normal", fr: "Normal", ru: "Норма" },
  "Over": { en: "Over", ro: "Supra", de: "Über", es: "Sobre", it: "Sopra", fr: "Sur", ru: "Избыток" },
  "Ideal Weight Range": { en: "Ideal Weight Range", ro: "Intervalul de Greutate Ideală", de: "Idealer Gewichtsbereich", es: "Rango de Peso Ideal", it: "Intervallo di Peso Ideale", fr: "Plage de Poids Idéale", ru: "Диапазон идеального веса" },
  "Excess Weight": { en: "Excess Weight", ro: "Greutate în Exces", de: "Übergewicht", es: "Exceso de Peso", it: "Peso in Eccesso", fr: "Excès de Poids", ru: "Избыточный вес" },
  "to reach your ideal weight range": { en: "to reach your ideal weight range", ro: "pentru a ajunge la intervalul de greutate ideală", de: "um Ihren idealen Gewichtsbereich zu erreichen", es: "para alcanzar su rango de peso ideal", it: "per raggiungere il tuo intervallo di peso ideale", fr: "pour atteindre votre plage de poids idéale", ru: "для достижения идеального веса" },
  "⚠️ For patients over 65, bariatric eligibility requires additional cardiac evaluation.": { en: "⚠️ For patients over 65, bariatric eligibility requires additional cardiac evaluation.", ro: "⚠️ Pentru pacienții peste 65 de ani, eligibilitatea bariatrică necesită evaluare cardiacă suplimentară.", de: "⚠️ Für Patienten über 65 erfordert die bariatrische Eignung eine zusätzliche kardiologische Untersuchung.", es: "⚠️ Para pacientes mayores de 65 años, la elegibilidad bariátrica requiere evaluación cardíaca adicional.", it: "⚠️ Per i pazienti sopra i 65 anni, l'idoneità bariatrica richiede un'ulteriore valutazione cardiologica.", fr: "⚠️ Pour les patients de plus de 65 ans, l'éligibilité bariatrique nécessite une évaluation cardiaque supplémentaire.", ru: "⚠️ Для пациентов старше 65 лет бариатрическое лечение требует дополнительного кардиологического обследования." },
  "Bariatric Surgery Eligible": { en: "Bariatric Surgery Eligible", ro: "Eligibil pentru Chirurgie Bariatrică", de: "Bariatrische Chirurgie geeignet", es: "Elegible para Cirugía Bariátrica", it: "Idoneo per Chirurgia Bariatrica", fr: "Éligible à la Chirurgie Bariatrique", ru: "Подходит для бариатрической хирургии" },
  "WHO Class II–III Obesity": { en: "WHO Class II–III Obesity", ro: "Obezitate WHO Clasa II–III", de: "WHO-Adipositas Grad II–III", es: "Obesidad Clase II-III de la OMS", it: "Obesità Classe II-III dell'OMS", fr: "Obésité de Classe II-III selon l'OMS", ru: "Ожирение II-III степени по ВОЗ" },
  "Based on your BMI, you meet the international clinical criteria (WHO/IFSO) for bariatric surgery. Gastric Sleeve or Bypass at Meva Clinic Istanbul could be the decisive step toward lasting weight loss.": { en: "Based on your BMI, you meet the international clinical criteria (WHO/IFSO) for bariatric surgery. Gastric Sleeve or Bypass at Meva Clinic Istanbul could be the decisive step toward lasting weight loss.", ro: "Pe baza IMC-ului dumneavoastră, îndepliniți criteriile clinice internaționale (WHO/IFSO) pentru chirurgia bariatrică. Gastric Sleeve sau Bypass la Meva Clinic Istanbul ar putea fi pasul decisiv spre pierderea durabilă în greutate.", de: "Aufgrund Ihres BMI erfüllen Sie die internationalen klinischen Kriterien (WHO/IFSO) für die bariatrische Chirurgie. Schlauchmagen oder Bypass in der Meva Clinic Istanbul könnten der entscheidende Schritt zur dauerhaften Gewichtsabnahme sein.", es: "Según su IMC, cumple los criterios clínicos internacionales (OMS/IFSO) para cirugía bariátrica. La Manga Gástrica o Bypass en Meva Clinic Estambul podría ser el paso decisivo hacia una pérdida de peso duradera.", it: "In base al tuo IMC, soddisfi i criteri clinici internazionali (OMS/IFSO) per la chirurgia bariatrica. Sleeve Gastrectomy o Bypass presso la Meva Clinic di Istanbul potrebbe essere il passo decisivo verso una perdita di peso duratura.", fr: "En fonction de votre IMC, vous répondez aux critères cliniques internationaux (OMS/IFSO) pour la chirurgie bariatrique. La Sleeve Gastrectomie ou le Bypass à la Clinique Meva d'Istanbul pourrait être l'étape décisive vers une perte de poids durable.", ru: "На основании вашего ИМТ вы соответствуете международным клиническим критериям (ВОЗ/IFSO) для бариатрической хирургии. Желудочное шунтирование или резекция в Meva Clinic Istanbul могут стать решающим шагом к длительной потере веса." },
  "Book Free Bariatric Consultation": { en: "Book Free Bariatric Consultation", ro: "Rezervați Consultație Bariatrică Gratuită", de: "Kostenlose bariatrische Beratung buchen", es: "Reservar Consulta Bariátrica Gratuita", it: "Prenota Consulto Bariatrico Gratuito", fr: "Réserver une Consultation Bariatrique Gratuite", ru: "Записаться на бесплатную бариатрическую консультацию" },
  "Full Name *": { en: "Full Name *", ro: "Nume Complet *", de: "Vollständiger Name *", es: "Nombre Completo *", it: "Nome e Cognome *", fr: "Nom Complet *", ru: "Полное имя *" },
  "Phone Number *": { en: "Phone Number *", ro: "Număr Telefon *", de: "Telefonnummer *", es: "Número de Teléfono *", it: "Numero di Telefono *", fr: "Numéro de Téléphone *", ru: "Номер телефона *" },
  "Sending…": { en: "Sending…", ro: "Se trimite…", de: "Senden…", es: "Enviando…", it: "Invio in corso…", fr: "Envoi en cours…", ru: "Отправка…" },
  "Request Callback in 15 min": { en: "Request Callback in 15 min", ro: "Solicitați Apel în 15 min", de: "Rückruf in 15 Min. anfordern", es: "Solicitar Llamada en 15 min", it: "Richiedi Richiamata in 15 min", fr: "Demander un Rappel dans 15 min", ru: "Заказать обратный звонок через 15 мин" },
  "✅ Request sent! A consultant will call within 15 minutes.": { en: "✅ Request sent! A consultant will call within 15 minutes.", ro: "✅ Cerere trimisă! Un consultant vă va suna în 15 minute.", de: "✅ Anfrage gesendet! Ein Berater wird sich innerhalb von 15 Minuten melden.", es: "✅ ¡Solicitud enviada! Un consultor llamará en 15 minutos.", it: "✅ Richiesta inviata! Un consulente ti chiamerà entro 15 minuti.", fr: "✅ Demande envoyée ! Un consultant vous appellera dans les 15 minutes.", ru: "✅ Запрос отправлен! Консультант перезвонит в течение 15 минут." },
  "⚕️ This tool is for informational purposes only and does not constitute medical advice. Always consult a qualified physician before making health decisions.": { en: "⚕️ This tool is for informational purposes only and does not constitute medical advice. Always consult a qualified physician before making health decisions.", ro: "⚕️ Acest instrument are scop informativ și nu constituie sfat medical. Consultați întotdeauna un medic calificat înainte de a lua decizii privind sănătatea.", de: "⚕️ Dieses Tool dient nur zu Informationszwecken und stellt keine medizinische Beratung dar. Konsultieren Sie immer einen qualifizierten Arzt, bevor Sie gesundheitliche Entscheidungen treffen.", es: "⚕️ Esta herramienta es solo para fines informativos y no constituye asesoramiento médico. Siempre consulte a un médico calificado antes de tomar decisiones sobre su salud.", it: "⚕️ Questo strumento ha solo scopo informativo e non costituisce parere medico. Consultare sempre un medico qualificato prima di prendere decisioni sulla salute.", fr: "⚕️ Cet outil est à titre informatif uniquement et ne constitue pas un avis médical. Consultez toujours un médecin qualifié avant de prendre des décisions concernant votre santé.", ru: "⚕️ Этот инструмент предназначен только для информационных целей и не является медицинской консультацией. Всегда консультируйтесь с квалифицированным врачом перед принятием решений о здоровье." },

  // PatientJourney
  "Online Consultation": { en: "Online Consultation", ro: "Consultație Online", de: "Online-Konsultation", es: "Consulta en línea", it: "Consulto Online", fr: "Consultation en Ligne", ru: "Онлайн Консультация" },
  "Submit your medical file. The specialist surgeon analyzes your case and responds within 24h with a personalized plan.": { en: "Submit your medical file. The specialist surgeon analyzes your case and responds within 24h with a personalized plan.", ro: "Trimiteți dosarul medical. Chirurgul specialist analizează cazul dvs. și răspunde în 24h cu un plan personalizat.", de: "Senden Sie Ihre Krankenakte. Der Facharzt analysiert Ihren Fall und antwortet innerhalb von 24 Stunden mit einem personalisierten Plan.", es: "Envíe su expediente médico. El cirujano especialista analiza su caso y responde en 24h con un plan personalizado.", it: "Invia la tua cartella clinica. Il chirurgo specialista analizza il tuo caso e risponde entro 24h con un piano personalizzato.", fr: "Soumettez votre dossier médical. Le chirurgien spécialiste analyse votre cas et répond sous 24h avec un plan personnalisé.", ru: "Отправьте свою медицинскую карту. Хирург-специалист анализирует ваш случай и отвечает в течение 24 часов с индивидуальным планом." },
  "VIP Arrival Istanbul": { en: "VIP Arrival Istanbul", ro: "Sosire VIP Istanbul", de: "VIP Ankunft Istanbul", es: "Llegada VIP a Estambul", it: "Arrivo VIP Istanbul", fr: "Arrivée VIP à Istanbul", ru: "VIP Прибытие в Стамбул" },
  "Private airport-hotel transfer with dedicated driver. Check-in at the 5-star partner hotel. Your coordinator is available 24/7.": { en: "Private airport-hotel transfer with dedicated driver. Check-in at the 5-star partner hotel. Your coordinator is available 24/7.", ro: "Transfer privat aeroport-hotel cu șofer dedicat. Check-in la hotelul partener de 5 stele. Coordonatorul dvs. este disponibil 24/7.", de: "Privater Flughafen-Hotel-Transfer mit engagiertem Fahrer. Check-in im 5-Sterne-Partnerhotel. Ihr Koordinator ist rund um die Uhr erreichbar.", es: "Traslado privado aeropuerto-hotel con conductor dedicado. Registro en el hotel asociado de 5 estrellas. Su coordinador está disponible las 24 horas, los 7 días de la semana.", it: "Trasferimento privato aeroporto-hotel con autista dedicato. Check-in presso l'hotel partner a 5 stelle. Il tuo coordinatore è disponibile 24 ore su 24, 7 giorni su 7.", fr: "Transfert privé aéroport-hôtel avec chauffeur dédié. Enregistrement à l'hôtel partenaire 5 étoiles. Votre coordinateur est disponible 24h/24 et 7j/7.", ru: "Частный трансфер аэропорт-отель с выделенным водителем. Заселение в партнерский 5-звездочный отель. Ваш координатор доступен круглосуточно." },
  "Clinical Excellence": { en: "Clinical Excellence", ro: "Excelență Clinică", de: "Klinische Exzellenz", es: "Excelencia Clínica", it: "Eccellenza Clinica", fr: "Excellence Clinique", ru: "Клиническое Превосходство" },
  "Complete pre-operative workup in JCI hospital. Surgical intervention with WHO protocols. 24/7 post-operative monitoring.": { en: "Complete pre-operative workup in JCI hospital. Surgical intervention with WHO protocols. 24/7 post-operative monitoring.", ro: "Investigații preoperatorii complete în spitalul JCI. Intervenția chirurgicală cu protocoale WHO. Monitorizare 24/7 post-operator.", de: "Vollständige präoperative Untersuchung in einem JCI-Krankenhaus. Chirurgischer Eingriff nach WHO-Protokollen. Rund-um-die-Uhr postoperative Überwachung.", es: "Estudio preoperatorio completo en hospital JCI. Intervención quirúrgica con protocolos de la OMS. Monitorización posoperatoria 24/7.", it: "Valutazione pre-operatoria completa in ospedale JCI. Intervento chirurgico con protocolli OMS. Monitoraggio post-operatorio 24 ore su 24, 7 giorni su 7.", fr: "Bilan préopératoire complet à l'hôpital JCI. Intervention chirurgicale selon les protocoles de l'OMS. Surveillance postopératoire 24h/24 et 7j/7.", ru: "Полное предоперационное обследование в больнице JCI. Хирургическое вмешательство по протоколам ВОЗ. Круглосуточный послеоперационный мониторинг." },
  "5-Star Recovery": { en: "5-Star Recovery", ro: "Recuperare 5 Stele", de: "5-Sterne Genesung", es: "Recuperación 5 Estrellas", it: "Recupero a 5 Stelle", fr: "Rétablissement 5 Étoiles", ru: "Восстановление 5 звезд" },
  "Premium hospital room or 5-star hotel. Dietary meals adapted to post-operative protocol. Physiotherapy and continuous care.": { en: "Premium hospital room or 5-star hotel. Dietary meals adapted to post-operative protocol. Physiotherapy and continuous care.", ro: "Cameră de spital premium sau hotel 5 stele. Mese dietetice adaptate protocolului post-operator. Fizioterapie și îngrijire continuă.", de: "Premium-Krankenhauszimmer oder 5-Sterne-Hotel. Diätmahlzeiten angepasst an das postoperative Protokoll. Physiotherapie und kontinuierliche Betreuung.", es: "Habitación de hospital premium u hotel de 5 estrellas. Comidas dietéticas adaptadas al protocolo posoperatorio. Fisioterapia y atención continua.", it: "Camera d'ospedale premium o hotel a 5 stelle. Pasti dietetici adattati al protocollo post-operatorio. Fisioterapia e cure continue.", fr: "Chambre d'hôpital premium ou hôtel 5 étoiles. Repas diététiques adaptés au protocole postopératoire. Physiothérapie et soins continus.", ru: "Палата премиум-класса или 5-звездочный отель. Диетическое питание, адаптированное к послеоперационному протоколу. Физиотерапия и постоянный уход." },
  "Lifetime Follow-up": { en: "Lifetime Follow-up", ro: "Follow-up Pe Viață", de: "Lebenslanges Follow-up", es: "Seguimiento de por Vida", it: "Follow-up a Vita", fr: "Suivi à Vie", ru: "Пожизненное наблюдение" },
  "Video consultations at 1, 3, and 6 months. Your coordinator is always available on WhatsApp. Meva results guarantee.": { en: "Video consultations at 1, 3, and 6 months. Your coordinator is always available on WhatsApp. Meva results guarantee.", ro: "Consultații video bilunare la 1, 3 și 6 luni. Coordonatorul dvs. este mereu disponibil pe WhatsApp. Garanția rezultatelor Meva.", de: "Videokonsultationen nach 1, 3 und 6 Monaten. Ihr Koordinator ist immer über WhatsApp erreichbar. Meva Ergebnisgarantie.", es: "Videoconsultas a los 1, 3 y 6 meses. Su coordinador está siempre disponible en WhatsApp. Garantía de resultados de Meva.", it: "Video consulti a 1, 3 e 6 mesi. Il tuo coordinatore è sempre disponibile su WhatsApp. Garanzia dei risultati Meva.", fr: "Consultations vidéo à 1, 3 et 6 mois. Votre coordinateur est toujours disponible sur WhatsApp. Garantie de résultats Meva.", ru: "Видеоконсультации через 1, 3 и 6 месяцев. Ваш координатор всегда на связи в WhatsApp. Гарантия результатов Meva." },
  "VIP Transfer": { en: "VIP Transfer", ro: "Transfer VIP", de: "VIP-Transfer", es: "Traslado VIP", it: "Trasferimento VIP", fr: "Transfert VIP", ru: "VIP Трансфер" },
  "Mercedes S-Class or premium SUV, bilingual driver, airport greeting with personalized sign.": { en: "Mercedes S-Class or premium SUV, bilingual driver, airport greeting with personalized sign.", ro: "Mercedes S-Class sau SUV premium, șofer bilingv, așteptare în aeroport cu tăbliță personalizată.", de: "Mercedes S-Klasse oder Premium-SUV, zweisprachiger Fahrer, Begrüßung am Flughafen mit personalisiertem Schild.", es: "Mercedes Clase S o SUV premium, conductor bilingüe, recepción en el aeropuerto con cartel personalizado.", it: "Mercedes Classe S o SUV premium, autista bilingue, accoglienza in aeroporto con cartello personalizzato.", fr: "Mercedes Classe S ou SUV premium, chauffeur bilingue, accueil à l'aéroport avec pancarte personnalisée.", ru: "Mercedes S-Class или внедорожник премиум-класса, двуязычный водитель, встреча в аэропорту с именной табличкой." },
  "5-Star Hotel": { en: "5-Star Hotel", ro: "Hotel 5 Stele", de: "5-Sterne Hotel", es: "Hotel de 5 Estrellas", it: "Hotel 5 Stelle", fr: "Hôtel 5 Étoiles", ru: "5-звездочный отель" },
  "Partners: Hilton Istanbul, InterContinental, Conrad Bosphorus. VIP single room included in package.": { en: "Partners: Hilton Istanbul, InterContinental, Conrad Bosphorus. VIP single room included in package.", ro: "Parteneri: Hilton Istanbul, InterContinental, Conrad Bosphorus. Camera single VIP inclusă în pachet.", de: "Partner: Hilton Istanbul, InterContinental, Conrad Bosporus. VIP-Einzelzimmer im Paket enthalten.", es: "Socios: Hilton Istanbul, InterContinental, Conrad Bosphorus. Habitación individual VIP incluida en el paquete.", it: "Partner: Hilton Istanbul, InterContinental, Conrad Bosphorus. Camera singola VIP inclusa nel pacchetto.", fr: "Partenaires : Hilton Istanbul, InterContinental, Conrad Bosphorus. Chambre individuelle VIP incluse dans le forfait.", ru: "Партнеры: Hilton Istanbul, InterContinental, Conrad Bosphorus. Одноместный VIP-номер включен в пакет." },
  "The Meva Experience": { en: "The Meva Experience", ro: "Experiența Meva", de: "Das Meva-Erlebnis", es: "La Experiencia Meva", it: "L'Esperienza Meva", fr: "L'Expérience Meva", ru: "Опыт Meva" },
  "Your Journey, ": { en: "Your Journey, ", ro: "Călătoria Ta, ", de: "Ihre Reise, ", es: "Su Viaje, ", it: "Il Tuo Viaggio, ", fr: "Votre Parcours, ", ru: "Ваше путешествие, " },
  "Step by Step": { en: "Step by Step", ro: "Pas cu Pas", de: "Schritt für Schritt", es: "Paso a Paso", it: "Passo dopo Passo", fr: "Étape par Étape", ru: "Шаг за Шагом" },
  "From your first message to your full recovery — every detail is managed with precision and luxury by our dedicated team.": { en: "From your first message to your full recovery — every detail is managed with precision and luxury by our dedicated team.", ro: "De la primul mesaj până la recuperarea completă — fiecare detaliu este gestionat cu precizie și lux de echipa noastră dedicată.", de: "Von Ihrer ersten Nachricht bis zu Ihrer vollständigen Genesung — jedes Detail wird von unserem engagierten Team mit Präzision und Luxus verwaltet.", es: "Desde su primer mensaje hasta su recuperación total, cada detalle es administrado con precisión y lujo por nuestro equipo dedicado.", it: "Dal primo messaggio alla completa guarigione — ogni dettaglio è gestito con precisione e lusso dal nostro team dedicato.", fr: "De votre premier message à votre complet rétablissement — chaque détail est géré avec précision et luxe par notre équipe dédiée.", ru: "От первого сообщения до полного выздоровления — каждая деталь управляется с точностью и роскошью нашей специальной командой." },
  "Next step": { en: "Next step", ro: "Următorul pas", de: "Nächster Schritt", es: "Siguiente paso", it: "Passo successivo", fr: "Étape suivante", ru: "Следующий шаг" },
  "VIP Logistics": { en: "VIP Logistics", ro: "Logistică VIP", de: "VIP-Logistik", es: "Logística VIP", it: "Logistica VIP", fr: "Logistique VIP", ru: "VIP Логистика" },
  "Comfort from the moment you land.": { en: "Comfort from the moment you land.", ro: "Confort din momentul aterizării.", de: "Komfort ab dem Moment der Landung.", es: "Comodidad desde el momento en que aterriza.", it: "Comfort dal momento in cui atterri.", fr: "Confort dès le moment où vous atterrissez.", ru: "Комфорт с момента приземления." },
  "Hello, I want to know more about the VIP all-inclusive package.": { en: "Hello, I want to know more about the VIP all-inclusive package.", ro: "Bună, aș dori să aflu mai multe despre pachetul VIP all-inclusive.", de: "Hallo, ich möchte mehr über das VIP All-Inclusive-Paket erfahren.", es: "Hola, quiero saber más sobre el paquete VIP todo incluido.", it: "Salve, vorrei saperne di più sul pacchetto VIP all-inclusive.", fr: "Bonjour, je souhaite en savoir plus sur le forfait VIP tout compris.", ru: "Здравствуйте, я хочу узнать больше о VIP-пакете «все включено»." },
  "Request VIP Package Details": { en: "Request VIP Package Details", ro: "Solicitați Detalii Pachet VIP", de: "VIP-Paketdetails anfordern", es: "Solicitar Detalles del Paquete VIP", it: "Richiedi Dettagli Pacchetto VIP", fr: "Demander les Détails du Forfait VIP", ru: "Запросить детали VIP-пакета" },

  // PremiumPackageSection
  "Premium Care": { en: "Premium Care", ro: "Îngrijire Premium", de: "Premium-Pflege", es: "Cuidado Premium", it: "Cure Premium", fr: "Soins Premium", ru: "Премиум-уход" },
  "All-Inclusive Package Built Around You": { en: "All-Inclusive Package Built Around You", ro: "Pachet All-Inclusive Construit în Jurul Tău", de: "All-Inclusive-Paket ganz auf Sie zugeschnitten", es: "Paquete Todo Incluido Construido a su Alrededor", it: "Pacchetto All-Inclusive Costruito Intorno a Te", fr: "Forfait Tout Compris Construit Autour de Vous", ru: "Пакет «Все включено», созданный для вас" },
  "Your medical experience in Istanbul should be stress-free. We have prepared a premium package where details make the difference.": { en: "Your medical experience in Istanbul should be stress-free. We have prepared a premium package where details make the difference.", ro: "Experiența ta medicală la Istanbul trebuie să fie lipsită de stres. Am pregătit un pachet premium în care detaliile fac diferența.", de: "Ihre medizinische Erfahrung in Istanbul sollte stressfrei sein. Wir haben ein Premium-Paket geschnürt, bei dem Details den Unterschied machen.", es: "Su experiencia médica en Estambul debe ser sin estrés. Hemos preparado un paquete premium donde los detalles marcan la diferencia.", it: "La tua esperienza medica a Istanbul dovrebbe essere senza stress. Abbiamo preparato un pacchetto premium in cui i dettagli fanno la differenza.", fr: "Votre expérience médicale à Istanbul doit être sans stress. Nous avons préparé un forfait premium où les détails font la différence.", ru: "Ваш медицинский опыт в Стамбуле должен быть свободным от стресса. Мы подготовили премиум-пакет, в котором детали имеют значение." },
  "VIP Airport & Clinic Transfer": { en: "VIP Airport & Clinic Transfer", ro: "VIP Transfer Aeroport & Clinică", de: "VIP-Flughafen- & Kliniktransfer", es: "Traslado VIP Aeropuerto y Clínica", it: "Trasferimento VIP Aeroporto e Clinica", fr: "Transfert VIP Aéroport et Clinique", ru: "VIP Трансфер Аэропорт и Клиника" },
  "Personal driver at your disposal from landing in Istanbul and throughout all medical visits.": { en: "Personal driver at your disposal from landing in Istanbul and throughout all medical visits.", ro: "Șofer personal la dispoziția ta de la aterizarea în Istanbul și pe parcursul tuturor vizitelor medicale.", de: "Persönlicher Fahrer steht Ihnen von der Landung in Istanbul und während aller medizinischen Besuche zur Verfügung.", es: "Conductor personal a su disposición desde el aterrizaje en Estambul y durante todas las visitas médicas.", it: "Autista personale a tua disposizione dallo sbarco a Istanbul e durante tutte le visite mediche.", fr: "Chauffeur personnel à votre disposition dès l'atterrissage à Istanbul et tout au long de toutes les visites médicales.", ru: "Личный водитель в вашем распоряжении с момента приземления в Стамбуле и на протяжении всех медицинских визитов." },
  "5-Star Hotel Accommodation": { en: "5-Star Hotel Accommodation", ro: "Cazare la Hotel 5 Stele", de: "5-Sterne-Hotelunterkunft", es: "Alojamiento en Hotel de 5 Estrellas", it: "Sistemazione in Hotel a 5 Stelle", fr: "Hébergement en Hôtel 5 Étoiles", ru: "Проживание в 5-звездочном отеле" },
  "Recovery in luxury conditions. The package fully covers accommodation in one of our prestigious partner hotels.": { en: "Recovery in luxury conditions. The package fully covers accommodation in one of our prestigious partner hotels.", ro: "Recuperare în condiții de lux. Pachetul acoperă integral cazarea într-unul dintre hotelurile partenere de prestigiu.", de: "Genesung unter luxuriösen Bedingungen. Das Paket deckt die Unterbringung in einem unserer renommierten Partnerhotels vollständig ab.", es: "Recuperación en condiciones de lujo. El paquete cubre íntegramente el alojamiento en uno de nuestros prestigiosos hoteles asociados.", it: "Recupero in condizioni di lusso. Il pacchetto copre integralmente la sistemazione in uno dei nostri prestigiosi hotel partner.", fr: "Récupération dans des conditions de luxe. Le forfait couvre entièrement l'hébergement dans l'un de nos prestigieux hôtels partenaires.", ru: "Восстановление в роскошных условиях. В пакет полностью входит проживание в одном из наших престижных отелей-партнеров." },
  "Native English Translator": { en: "Native English Translator", ro: "Traducător (Română - Engleză)", de: "Muttersprachlicher Übersetzer", es: "Traductor Nativo", it: "Traduttore Madrelingua", fr: "Traducteur Natif", ru: "Переводчик-носитель языка" },
  "There will be no language barriers. A dedicated medical assistant will accompany you to translate every detail.": { en: "There will be no language barriers. A dedicated medical assistant will accompany you to translate every detail.", ro: "Nu vor exista bariere lingvistice. Asistentul medical dedicat te va însoți pentru a traduce fiecare detaliu.", de: "Es wird keine Sprachbarrieren geben. Ein engagierter medizinischer Assistent wird Sie begleiten, um jedes Detail zu übersetzen.", es: "No habrá barreras del idioma. Un asistente médico dedicado lo acompañará para traducir cada detalle.", it: "Non ci saranno barriere linguistiche. Un assistente medico dedicato ti accompagnerà per tradurre ogni dettaglio.", fr: "Il n'y aura pas de barrières linguistiques. Un assistant médical dédié vous accompagnera pour traduire chaque détail.", ru: "Языковых барьеров не будет. Специальный медицинский ассистент будет сопровождать вас, чтобы перевести каждую деталь." },
  "Pre/Post-Operative Tests": { en: "Pre/Post-Operative Tests", ro: "Teste Pre/Post-Operatorii", de: "Prä-/Postoperative Tests", es: "Pruebas Pre/Posoperatorias", it: "Test Pre/Post-Operatori", fr: "Tests Pré/Postopératoires", ru: "Пре/Постоперационные Тесты" },
  "All analyzes, consultations (cardiological, anesthetic) and necessary tests are 100% covered.": { en: "All analyzes, consultations (cardiological, anesthetic) and necessary tests are 100% covered.", ro: "Toate analizele, consulturile (cardiologic, anestezic) și testele necesare sunt acoperite 100%.", de: "Alle Analysen, Konsultationen (kardiologisch, anästhetisch) und notwendigen Tests sind zu 100% abgedeckt.", es: "Todos los análisis, consultas (cardiológicas, anestésicas) y pruebas necesarias están cubiertos al 100%.", it: "Tutte le analisi, consulti (cardiologici, anestesiologici) e gli esami necessari sono coperti al 100%.", fr: "Toutes les analyses, consultations (cardiologiques, anesthésiques) et tests nécessaires sont couverts à 100%.", ru: "Все анализы, консультации (кардиологические, анестезиологические) и необходимые тесты покрываются на 100%." },
  "The Premium Treatment": { en: "The Premium Treatment", ro: "Tratamentul Premium", de: "Die Premium-Behandlung", es: "El Tratamiento Premium", it: "Il Trattamento Premium", fr: "Le Traitement Premium", ru: "Премиум-Лечение" },
  "Guaranteed Surgical Intervention": { en: "Guaranteed Surgical Intervention", ro: "Intervenția Chirurgicală Garantată", de: "Garantierter chirurgischer Eingriff", es: "Intervención Quirúrgica Garantizada", it: "Intervento Chirurgico Garantito", fr: "Intervention Chirurgicale Garantie", ru: "Гарантированное хирургическое вмешательство" },
  "Team formed by Doctor Professors": { en: "Team formed by Doctor Professors", ro: "Echipă formată din Profesori Doctori", de: "Team aus Professor Doktoren", es: "Equipo formado por Médicos Profesores", it: "Team formato da Professori Dottori", fr: "Équipe formée par des Professeurs Docteurs", ru: "Команда, состоящая из врачей-профессоров" },
  "VIP Hospitalization in Private Clinic (1-3 Days)": { en: "VIP Hospitalization in Private Clinic (1-3 Days)", ro: "Spitalizare VIP în Clinică Privată (1-3 Zile)", de: "VIP-Krankenhausaufenthalt in Privatklinik (1-3 Tage)", es: "Hospitalización VIP en Clínica Privada (1-3 Días)", it: "Ricovero VIP in Clinica Privata (1-3 Giorni)", fr: "Hospitalisation VIP en Clinique Privée (1-3 Jours)", ru: "VIP Госпитализация в Частной Клинике (1-3 дня)" },
  "Home Medication Included": { en: "Home Medication Included", ro: "Medicamentația pentru Acasă Inclusă", de: "Heimmedikation inbegriffen", es: "Medicación para el hogar incluida", it: "Farmaci per la Casa Inclusi", fr: "Médicaments à Domicile Inclus", ru: "Домашние Лекарства Включены" },
  "Dedicated Post-Operative Diet Plan": { en: "Dedicated Post-Operative Diet Plan", ro: "Plan de Dieta Dedicat Post-Operator", de: "Spezieller postoperativer Diätplan", es: "Plan de Dieta Posoperatoria Dedicado", it: "Piano Dietetico Post-Operatorio Dedicato", fr: "Plan de Régime Postopératoire Dédié", ru: "Специализированный послеоперационный план питания" },
  "\"No hidden costs – Everything included for your comfort\"": { en: "\"No hidden costs – Everything included for your comfort\"", ro: "\"Fără costuri ascunse – Totul inclus pentru confortul tău\"", de: "\"Keine versteckten Kosten – Alles für Ihren Komfort inbegriffen\"", es: "\"Sin costos ocultos – Todo incluido para su comodidad\"", it: "\"Nessun costo nascosto – Tutto incluso per il tuo comfort\"", fr: "\"Aucun coût caché – Tout est inclus pour votre confort\"", ru: "\"Никаких скрытых затрат – Все включено для вашего комфорта\"" }
};

const transPath = path.join(__dirname, 'utils/uiTranslations.ts');
let transContent = fs.readFileSync(transPath, 'utf-8');

let translationStr = '';
for (const [key, val] of Object.entries(newTranslations)) {
  translationStr += `  ${JSON.stringify(key)}: ${JSON.stringify(val)},\n`;
}

if (!transContent.includes('"BMI Calculator & "')) {
  transContent = transContent.replace(/export const T: Record<string, Record<string, string>> = \{/, 'export const T: Record<string, Record<string, string>> = {\n' + translationStr);
  fs.writeFileSync(transPath, transContent, 'utf-8');
  console.log('Added translations to uiTranslations.ts');
} else {
  console.log('Translations already in uiTranslations.ts');
}
